Feature/automating android
Leanplum/Leanplum-Android-SDK-Example pull request #1
Opened 2017-06-29 23:51 UTC by sayaansaha

1. updated settings.gradle to include :AndroidSDK
2. updated AndroidManifest.xml corrected <intent-filter> to properly add app to App Launcher
3. Created a Load test with button

2017-06-30 18:48 UTC, benmarten requested changes
thanks for your changes. If you could take a moment to implement the changes it would be awesome! Thanks :)

2017-06-30 18:48 UTC, benmarten commented on .idea/gradle.xml
> +            <option value="$PROJECT_DIR$/../Leanplum-Android-SDK/AndroidSDK" />
can u please add the UIEditor in the same manner?

2017-06-30 18:48 UTC, benmarten commented on app/build.gradle
> +def LP_VERSION = System.getenv('VERSION') ?: '2.2.3-SNAPSHOT.167';
let's point this to the latest stable version for now ;) 2.2.2

2017-06-30 18:48 UTC, benmarten commented on app/build.gradle
> +    sourcesReleaseCompile project(path: ':AndroidSDK', configuration: 'release')
add uieditor here please

2017-06-30 18:48 UTC, benmarten commented on app/src/main/java/com/leanplum/android/example/Configure.java
> +  static final String API_HOST_NAME = "leanplum-qa-1372.appspot.com";
lets' actually point this to the prod api host name, `api.leanplum.com`

2017-06-30 18:48 UTC, benmarten commented on app/src/main/java/com/leanplum/android/example/Configure.java
> +  static final String SOCKET_HOST_NAME = "dev-qa.leanplum.com";
revert

2017-06-30 18:48 UTC, benmarten commented on app/src/main/java/com/leanplum/android/example/fragments/PushNotificationsFragment.java
> +        for(int i=0; i < 10002; i++) {
can you press code auto format in android studio please?

2017-06-30 18:48 UTC, benmarten commented on app/src/main/java/com/leanplum/android/example/fragments/PushNotificationsFragment.java
> +          Leanplum.track("Load TestF");
improve the string a little bit, how about `"load_test_iteration" + i`

2017-06-30 18:48 UTC, benmarten commented on app/src/main/res/layout/show_example_layout.xml
> +    <Button
can we align/center the button nicely please?

2017-06-30 18:48 UTC, benmarten commented on settings.gradle
>  include ':app'
add uieditor as well please

2017-06-30 18:49 UTC, benmarten commented
please limit to 1/2 reviewers. generally only one reviewer is required. if its a big or critical change, two reviewers are ok too...

2017-06-30 19:07 UTC, sayaansaha commented on app/build.gradle
> +def LP_VERSION = System.getenv('VERSION') ?: '2.2.3-SNAPSHOT.167';
of course!

2017-07-05 17:55 UTC, benmarten approved these changes
awesome! thx!!!!

2017-07-05 17:56 UTC, benmarten commented
if you get a chance, can you align the button nicely please? ;)

2017-07-05 20:23 UTC, merged